name: build
on:
  schedule:
    - cron: "30 0 * * FRI"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.2'
    - name: Setup Elvish
      uses: elves/setup-elvish@v1
      with:
        elvish-version: 0.20.1
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - name: Build & Push
      run: |
        ./build.elv
